// <auto-generated />
using System;
using KyTucXaManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KyTucXaManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("KyTucXaManagement.Models.ChiSoDien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ChiSoCuoi")
                        .HasColumnType("REAL");

                    b.Property<double>("ChiSoDau")
                        .HasColumnType("REAL");

                    b.Property<double>("DonGia")
                        .HasColumnType("REAL");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nam")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayGhi")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Thang")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhongId");

                    b.ToTable("ChiSoDiens");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.ChiSoNuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ChiSoCuoi")
                        .HasColumnType("REAL");

                    b.Property<double>("ChiSoDau")
                        .HasColumnType("REAL");

                    b.Property<double>("DonGia")
                        .HasColumnType("REAL");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nam")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayGhi")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Thang")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhongId");

                    b.ToTable("ChiSoNuocs");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.DonYeuCau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiDon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiDuyet")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhongId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("DonYeuCaus");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HanThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nam")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<double>("PhiKhac")
                        .HasColumnType("REAL");

                    b.Property<int?>("PhongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Thang")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TienDien")
                        .HasColumnType("REAL");

                    b.Property<double>("TienNuoc")
                        .HasColumnType("REAL");

                    b.Property<double>("TienPhong")
                        .HasColumnType("REAL");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhongId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.Phong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("GiaPhong")
                        .HasColumnType("REAL");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoNguoiHienTai")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SucChua")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tang")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToaNha")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaPhong")
                        .IsUnique();

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DienUuTien")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayVaoKTX")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaSinhVien")
                        .IsUnique();

                    b.HasIndex("PhongId");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.SuCoTaiSan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ChiPhiSua")
                        .HasColumnType("REAL");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTaSuCo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MucDo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayBao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiSua")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SinhVienBaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaiSanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SinhVienBaoId");

                    b.HasIndex("TaiSanId");

                    b.ToTable("SuCoTaiSans");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.TaiSan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("GiaTri")
                        .HasColumnType("REAL");

                    b.Property<string>("LoaiTaiSan")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaTaiSan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenTaiSan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhongId");

                    b.ToTable("TaiSans");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.TheKTX", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaThe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("TEXT");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SinhVienId")
                        .IsUnique();

                    b.ToTable("TheKTXs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KyTucXaManagement.Models.ChiSoDien", b =>
                {
                    b.HasOne("KyTucXaManagement.Models.Phong", "Phong")
                        .WithMany("ChiSoDiens")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.ChiSoNuoc", b =>
                {
                    b.HasOne("KyTucXaManagement.Models.Phong", "Phong")
                        .WithMany("ChiSoNuocs")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.DonYeuCau", b =>
                {
                    b.HasOne("KyTucXaManagement.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("PhongId");

                    b.HasOne("KyTucXaManagement.Models.SinhVien", "SinhVien")
                        .WithMany("DonYeuCaus")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.HoaDon", b =>
                {
                    b.HasOne("KyTucXaManagement.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("PhongId");

                    b.HasOne("KyTucXaManagement.Models.SinhVien", "SinhVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.SinhVien", b =>
                {
                    b.HasOne("KyTucXaManagement.Models.Phong", "Phong")
                        .WithMany("SinhViens")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.SuCoTaiSan", b =>
                {
                    b.HasOne("KyTucXaManagement.Models.SinhVien", "SinhVienBao")
                        .WithMany()
                        .HasForeignKey("SinhVienBaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KyTucXaManagement.Models.TaiSan", "TaiSan")
                        .WithMany("SuCoTaiSans")
                        .HasForeignKey("TaiSanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVienBao");

                    b.Navigation("TaiSan");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.TaiSan", b =>
                {
                    b.HasOne("KyTucXaManagement.Models.Phong", "Phong")
                        .WithMany("TaiSans")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.TheKTX", b =>
                {
                    b.HasOne("KyTucXaManagement.Models.SinhVien", "SinhVien")
                        .WithOne("TheKTX")
                        .HasForeignKey("KyTucXaManagement.Models.TheKTX", "SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KyTucXaManagement.Models.Phong", b =>
                {
                    b.Navigation("ChiSoDiens");

                    b.Navigation("ChiSoNuocs");

                    b.Navigation("SinhViens");

                    b.Navigation("TaiSans");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.SinhVien", b =>
                {
                    b.Navigation("DonYeuCaus");

                    b.Navigation("HoaDons");

                    b.Navigation("TheKTX");
                });

            modelBuilder.Entity("KyTucXaManagement.Models.TaiSan", b =>
                {
                    b.Navigation("SuCoTaiSans");
                });
#pragma warning restore 612, 618
        }
    }
}
